//! GENERATED by fluessig bindgen from crates/fluessig/entl.tsp (api layer). Do not edit.
//! Regenerate: `bun run gen` in crates/entl-node. Hand-written half: crate::core_impl.
//! straitjacket-allow-file:duplication — generated code repeats by design.
#![allow(clippy::all)]

use pyo3::exceptions::PyRuntimeError;
use pyo3::prelude::*;
use std::sync::Arc;
use std::time::Duration;

fn err(e: impl std::fmt::Display) -> PyErr {
    PyRuntimeError::new_err(e.to_string())
}

/// One poll result from a core stream (the sync primitive every stream shape dresses).
pub enum Poll<T> {
    Item(T),
    Idle,
    Closed,
}

/// The one sync primitive: a blocking, timeout-bounded poll.
pub trait PollStream<T>: Send + Sync {
    fn poll(&self, timeout: Duration) -> Poll<T>;
}

/// Bulk bytes cross into Python as `bytes` (Arrow IPC payloads and friends).
pub type Bytes = Vec<u8>;

#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq)]
pub enum SinkTarget {
    Sqlite,
    Jsonl,
    Postgres,
}

/// What one git load produced.
#[pyclass(get_all)]
#[derive(Clone)]
pub struct GitStats {
    pub new_commits: i64,
    pub file_changes: i64,
    pub refs: i64,
}
#[pymethods]
impl GitStats {
    #[new]
    #[pyo3(signature = (new_commits, file_changes, refs))]
    fn new(new_commits: i64, file_changes: i64, refs: i64) -> Self {
        Self {
            new_commits,
            file_changes,
            refs,
        }
    }
}

/// What one GitHub load produced.
#[pyclass(get_all)]
#[derive(Clone)]
pub struct GithubStats {
    pub events: i64,
    pub pull_requests: i64,
    pub reviews: i64,
    pub review_comments: i64,
    pub issues: i64,
    pub comments: i64,
    pub workflow_runs: i64,
    pub check_runs: i64,
    pub users: i64,
}
#[pymethods]
impl GithubStats {
    #[new]
    #[pyo3(signature = (events, pull_requests, reviews, review_comments, issues, comments, workflow_runs, check_runs, users))]
    fn new(
        events: i64,
        pull_requests: i64,
        reviews: i64,
        review_comments: i64,
        issues: i64,
        comments: i64,
        workflow_runs: i64,
        check_runs: i64,
        users: i64,
    ) -> Self {
        Self {
            events,
            pull_requests,
            reviews,
            review_comments,
            issues,
            comments,
            workflow_runs,
            check_runs,
            users,
        }
    }
}

/// What a sink() cycle produced: git + forge counts, and rows applied to the target.
#[pyclass(get_all)]
#[derive(Clone)]
pub struct SinkStats {
    pub new_commits: i64,
    pub file_changes: i64,
    pub refs: i64,
    pub pull_requests: i64,
    pub issues: i64,
    pub events: i64,
    pub workflow_runs: i64,
    pub check_runs: i64,
    pub rows: i64,
}
#[pymethods]
impl SinkStats {
    #[new]
    #[pyo3(signature = (new_commits, file_changes, refs, pull_requests, issues, events, workflow_runs, check_runs, rows))]
    fn new(
        new_commits: i64,
        file_changes: i64,
        refs: i64,
        pull_requests: i64,
        issues: i64,
        events: i64,
        workflow_runs: i64,
        check_runs: i64,
        rows: i64,
    ) -> Self {
        Self {
            new_commits,
            file_changes,
            refs,
            pull_requests,
            issues,
            events,
            workflow_runs,
            check_runs,
            rows,
        }
    }
}

/// One changed file between two commits.
#[pyclass(get_all)]
#[derive(Clone)]
pub struct FileDiff {
    pub path: String,
    pub old_path: Option<String>,
    pub status: String,
    pub additions: i64,
    pub deletions: i64,
    pub patch: String,
}
#[pymethods]
impl FileDiff {
    #[new]
    #[pyo3(signature = (path, status, additions, deletions, patch, old_path=None))]
    fn new(
        path: String,
        status: String,
        additions: i64,
        deletions: i64,
        patch: String,
        old_path: Option<String>,
    ) -> Self {
        Self {
            path,
            status,
            additions,
            deletions,
            patch,
            old_path,
        }
    }
}

/// One change-stream batch. The rows stay columnar (Arrow): `ipc` yields them as
/// one Arrow IPC stream (a single RecordBatch, schema included), and the Python
/// class additionally speaks the Arrow PyCapsule protocol for zero-copy import
/// (`pa.record_batch(batch)`). Values are native Arrow types — oids are Binary,
/// timestamps Timestamp(µs) — unlike query()/extract()'s canonical JSON (hex
/// oids, RFC3339). No per-row `_op`: `op`/`table` ride this envelope.
#[pyclass]
#[derive(Clone)]
pub struct ChangeBatch {
    pub(crate) table: String,
    pub(crate) op: String,
    // the rows, still columnar — capsule-exported or encoded on demand
    pub(crate) batch: entl_core::RecordBatch,
}
#[pymethods]
impl ChangeBatch {
    #[getter]
    fn table(&self) -> String {
        self.table.clone()
    }
    #[getter]
    fn op(&self) -> String {
        self.op.clone()
    }
    /// The rows as one Arrow IPC stream (`pyarrow.ipc.open_stream`-able) —
    /// for consumers that want bytes rather than the zero-copy capsules.
    fn ipc(&self) -> PyResult<Bytes> {
        entl_core::batch_ipc(&self.batch).map_err(err)
    }
    /// Arrow PyCapsule interface — the schema half of the C Data Interface.
    fn __arrow_c_schema__(&self, py: Python<'_>) -> PyResult<Py<pyo3::types::PyCapsule>> {
        let (_, schema) = entl_core::batch_to_ffi(&self.batch).map_err(err)?;
        let name = std::ffi::CString::new("arrow_schema").expect("static cstr");
        Ok(pyo3::types::PyCapsule::new(py, schema, Some(name))?.unbind())
    }
    /// Arrow PyCapsule interface — (schema, array) capsules; `pa.record_batch(batch)`
    /// imports the rows zero-copy. `requested_schema` is accepted and ignored (spec-permitted).
    #[pyo3(signature = (requested_schema=None))]
    fn __arrow_c_array__(
        &self,
        py: Python<'_>,
        requested_schema: Option<Bound<'_, PyAny>>,
    ) -> PyResult<(Py<pyo3::types::PyCapsule>, Py<pyo3::types::PyCapsule>)> {
        let _ = requested_schema;
        let (array, schema) = entl_core::batch_to_ffi(&self.batch).map_err(err)?;
        let sname = std::ffi::CString::new("arrow_schema").expect("static cstr");
        let aname = std::ffi::CString::new("arrow_array").expect("static cstr");
        let s = pyo3::types::PyCapsule::new(py, schema, Some(sname))?.unbind();
        let a = pyo3::types::PyCapsule::new(py, array, Some(aname))?.unbind();
        Ok((s, a))
    }
}

/// One driver-plan statement: the host runs it verbatim against its own client.
#[pyclass(get_all)]
#[derive(Clone)]
pub struct Statement {
    pub sql: String,
    pub params: String,
    pub table: Option<String>,
}
#[pymethods]
impl Statement {
    #[new]
    #[pyo3(signature = (sql, params, table=None))]
    fn new(sql: String, params: String, table: Option<String>) -> Self {
        Self { sql, params, table }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct TableRename {
    pub from_: String,
    pub to: String,
}
#[pymethods]
impl TableRename {
    #[new]
    #[pyo3(signature = (from_, to))]
    fn new(from_: String, to: String) -> Self {
        Self { from_, to }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct SinkOptions {
    pub target: SinkTarget,
    pub path: Option<String>,
    pub github: Option<bool>,
    pub tables: Option<Vec<String>>,
    pub exclude: Option<Vec<String>>,
    pub rename: Option<Vec<TableRename>>,
    pub schema: Option<String>,
    pub objects: Option<bool>,
}
#[pymethods]
impl SinkOptions {
    #[new]
    #[pyo3(signature = (target, path=None, github=None, tables=None, exclude=None, rename=None, schema=None, objects=None))]
    fn new(
        target: SinkTarget,
        path: Option<String>,
        github: Option<bool>,
        tables: Option<Vec<String>>,
        exclude: Option<Vec<String>>,
        rename: Option<Vec<TableRename>>,
        schema: Option<String>,
        objects: Option<bool>,
    ) -> Self {
        Self {
            target,
            path,
            github,
            tables,
            exclude,
            rename,
            schema,
            objects,
        }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct ExtractOptions {
    pub source: String,
    pub path: String,
    pub tables: Option<Vec<String>>,
    pub schema: Option<String>,
}
#[pymethods]
impl ExtractOptions {
    #[new]
    #[pyo3(signature = (source, path, tables=None, schema=None))]
    fn new(
        source: String,
        path: String,
        tables: Option<Vec<String>>,
        schema: Option<String>,
    ) -> Self {
        Self {
            source,
            path,
            tables,
            schema,
        }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct RebuildOptions {
    pub source: String,
    pub dest: String,
    pub out: String,
    pub schema: Option<String>,
}
#[pymethods]
impl RebuildOptions {
    #[new]
    #[pyo3(signature = (source, dest, out, schema=None))]
    fn new(source: String, dest: String, out: String, schema: Option<String>) -> Self {
        Self {
            source,
            dest,
            out,
            schema,
        }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct ChangesOptions {
    pub github: Option<bool>,
    pub objects: Option<bool>,
}
#[pymethods]
impl ChangesOptions {
    #[new]
    #[pyo3(signature = (github=None, objects=None))]
    fn new(github: Option<bool>, objects: Option<bool>) -> Self {
        Self { github, objects }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct DriverPlanOptions {
    pub tables: Option<Vec<String>>,
    pub exclude: Option<Vec<String>>,
    pub rename: Option<Vec<TableRename>>,
    pub schema: Option<String>,
}
#[pymethods]
impl DriverPlanOptions {
    #[new]
    #[pyo3(signature = (tables=None, exclude=None, rename=None, schema=None))]
    fn new(
        tables: Option<Vec<String>>,
        exclude: Option<Vec<String>>,
        rename: Option<Vec<TableRename>>,
        schema: Option<String>,
    ) -> Self {
        Self {
            tables,
            exclude,
            rename,
            schema,
        }
    }
}

/// The `Git` contract — implement over the engine in `crate::core_impl`.
pub trait GitCore: Sized + Send + Sync + 'static {
    fn diff_commits(
        repo_path: String,
        base: String,
        head: String,
        three_dot: bool,
    ) -> anyhow::Result<Vec<FileDiff>>;
    fn file_at(repo_path: String, commit: String, path: String) -> anyhow::Result<Option<String>>;
    fn branch_exists(repo_path: String, name: String) -> anyhow::Result<bool>;
    fn current_branch(repo_path: String) -> anyhow::Result<String>;
    fn commit_bodies(repo_path: String, branch: String) -> anyhow::Result<String>;
    fn ls_remote_heads(repo_path: String, pattern: String) -> anyhow::Result<Vec<String>>;
}

/// The `Entl` contract — implement over the engine in `crate::core_impl`.
pub trait EntlCore: Sized + Send + Sync + 'static {
    fn open(db_path: String) -> anyhow::Result<Self>;
    fn load_git(&self, repo_path: String) -> anyhow::Result<GitStats>;
    fn load_github(&self, repo_path: String) -> anyhow::Result<GithubStats>;
    fn query(&self, sql: String) -> anyhow::Result<String>;
    fn query_arrow(&self, sql: String) -> anyhow::Result<Bytes>;
    fn sink(&self, repo_path: String, options: SinkOptions) -> anyhow::Result<SinkStats>;
    fn extract(&self, options: ExtractOptions) -> anyhow::Result<String>;
    fn changes(
        &self,
        repo_path: String,
        options: Option<ChangesOptions>,
    ) -> anyhow::Result<Box<dyn PollStream<ChangeBatch>>>;
    fn driver_plan(
        &self,
        options: Option<DriverPlanOptions>,
    ) -> anyhow::Result<Box<dyn PollStream<Statement>>>;
    fn rebuild(&self, options: RebuildOptions) -> anyhow::Result<i64>;
}

/// Diff two commits (`base...head` when threeDot).
#[pyfunction]
#[pyo3(signature = (repo_path, base, head, three_dot))]
fn diff_commits(
    py: Python<'_>,
    repo_path: String,
    base: String,
    head: String,
    three_dot: bool,
) -> PyResult<Vec<FileDiff>> {
    py.detach(move || {
        <crate::core_impl::GitImpl as GitCore>::diff_commits(repo_path, base, head, three_dot)
    })
    .map_err(err)
}

/// A file's content at a commit — null when absent or binary.
#[pyfunction]
#[pyo3(signature = (repo_path, commit, path))]
fn file_at(
    py: Python<'_>,
    repo_path: String,
    commit: String,
    path: String,
) -> PyResult<Option<String>> {
    py.detach(move || <crate::core_impl::GitImpl as GitCore>::file_at(repo_path, commit, path))
        .map_err(err)
}

#[pyfunction]
#[pyo3(signature = (repo_path, name))]
fn branch_exists(py: Python<'_>, repo_path: String, name: String) -> PyResult<bool> {
    py.detach(move || <crate::core_impl::GitImpl as GitCore>::branch_exists(repo_path, name))
        .map_err(err)
}

#[pyfunction]
#[pyo3(signature = (repo_path))]
fn current_branch(py: Python<'_>, repo_path: String) -> PyResult<String> {
    py.detach(move || <crate::core_impl::GitImpl as GitCore>::current_branch(repo_path))
        .map_err(err)
}

/// Commit subjects+bodies along a branch (JSON).
#[pyfunction]
#[pyo3(signature = (repo_path, branch))]
fn commit_bodies(py: Python<'_>, repo_path: String, branch: String) -> PyResult<String> {
    py.detach(move || <crate::core_impl::GitImpl as GitCore>::commit_bodies(repo_path, branch))
        .map_err(err)
}

/// Remote branch names matching a pattern (trailing-`*` glob). Fetches first.
#[pyfunction]
#[pyo3(signature = (repo_path, pattern))]
fn ls_remote_heads(py: Python<'_>, repo_path: String, pattern: String) -> PyResult<Vec<String>> {
    py.detach(move || <crate::core_impl::GitImpl as GitCore>::ls_remote_heads(repo_path, pattern))
        .map_err(err)
}

/// Poll-based stream from `Entl.changes`, dressed as a Python iterator.
#[pyclass]
pub struct Changes {
    stream: Box<dyn PollStream<ChangeBatch>>,
}
#[pymethods]
impl Changes {
    fn __iter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> {
        slf
    }
    fn __next__(&self, py: Python<'_>) -> Option<ChangeBatch> {
        py.detach(|| loop {
            match self.stream.poll(Duration::from_millis(500)) {
                Poll::Item(v) => return Some(v),
                Poll::Idle => continue,
                Poll::Closed => return None, // None => StopIteration
            }
        })
    }
}

/// Poll-based stream from `Entl.driverPlan`, dressed as a Python iterator.
#[pyclass]
pub struct DriverPlan {
    stream: Box<dyn PollStream<Statement>>,
}
#[pymethods]
impl DriverPlan {
    fn __iter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> {
        slf
    }
    fn __next__(&self, py: Python<'_>) -> Option<Statement> {
        py.detach(|| loop {
            match self.stream.poll(Duration::from_millis(500)) {
                Poll::Item(v) => return Some(v),
                Poll::Idle => continue,
                Poll::Closed => return None, // None => StopIteration
            }
        })
    }
}

/// An open entl database. Heavy ops are unary (off-thread in async hosts).
#[pyclass]
pub struct Entl {
    // pub(crate): @manual ops in lib.rs extend this class and need the core
    pub(crate) core: Arc<crate::core_impl::EntlImpl>,
}

#[pymethods]
impl Entl {
    /// Open (or create) the .duckdb at `dbPath` and apply the schema.
    #[new]
    fn new(db_path: String) -> PyResult<Self> {
        Ok(Self {
            core: Arc::new(<crate::core_impl::EntlImpl as EntlCore>::open(db_path).map_err(err)?),
        })
    }
    /// Load git history from `repoPath` (one-way, incremental).
    #[pyo3(signature = (repo_path))]
    fn load_git(&self, py: Python<'_>, repo_path: String) -> PyResult<GitStats> {
        let core = self.core.clone();
        py.detach(move || core.load_git(repo_path)).map_err(err)
    }
    /// Load GitHub data (events/PRs/issues/Actions). Needs a token.
    #[pyo3(signature = (repo_path))]
    fn load_github(&self, py: Python<'_>, repo_path: String) -> PyResult<GithubStats> {
        let core = self.core.clone();
        py.detach(move || core.load_github(repo_path)).map_err(err)
    }
    /// Run a SQL query; JSON rows back.
    #[pyo3(signature = (sql))]
    fn query(&self, py: Python<'_>, sql: String) -> PyResult<String> {
        let core = self.core.clone();
        py.detach(move || core.query(sql)).map_err(err)
    }
    /// Run a SQL query; the result as one Arrow IPC stream (schema + all batches) —
    /// the dataframe on-ramp (pyarrow → pandas/polars, apache-arrow JS, red-arrow).
    #[pyo3(signature = (sql))]
    fn query_arrow(&self, py: Python<'_>, sql: String) -> PyResult<Bytes> {
        let core = self.core.clone();
        py.detach(move || core.query_arrow(sql)).map_err(err)
    }
    /// Pull `repoPath` and sync it into a target store, in one call.
    #[pyo3(signature = (repo_path, target, path=None, github=None, tables=None, exclude=None, rename=None, schema=None, objects=None))]
    fn sink(
        &self,
        py: Python<'_>,
        repo_path: String,
        target: SinkTarget,
        path: Option<String>,
        github: Option<bool>,
        tables: Option<Vec<String>>,
        exclude: Option<Vec<String>>,
        rename: Option<Vec<TableRename>>,
        schema: Option<String>,
        objects: Option<bool>,
    ) -> PyResult<SinkStats> {
        let sink_options_arg = SinkOptions {
            target,
            path,
            github,
            tables,
            exclude,
            rename,
            schema,
            objects,
        };

        let core = self.core.clone();
        py.detach(move || core.sink(repo_path, sink_options_arg))
            .map_err(err)
    }
    /// Read a store back into canonical rows (JSON; oids hex, timestamps RFC3339).
    #[pyo3(signature = (source, path, tables=None, schema=None))]
    fn extract(
        &self,
        py: Python<'_>,
        source: String,
        path: String,
        tables: Option<Vec<String>>,
        schema: Option<String>,
    ) -> PyResult<String> {
        let extract_options_arg = ExtractOptions {
            source,
            path,
            tables,
            schema,
        };

        let core = self.core.clone();
        py.detach(move || core.extract(extract_options_arg))
            .map_err(err)
    }
    /// Stream the change batches from one pull (the stream plane).
    #[pyo3(signature = (repo_path, github=None, objects=None))]
    fn changes(
        &self,
        repo_path: String,
        github: Option<bool>,
        objects: Option<bool>,
    ) -> PyResult<Changes> {
        let changes_options_arg = ChangesOptions { github, objects };

        Ok(Changes {
            stream: self
                .core
                .changes(repo_path, Some(changes_options_arg))
                .map_err(err)?,
        })
    }
    /// Backfill this store into a driver target: stream {sql, params} for the host to execute.
    #[pyo3(signature = (tables=None, exclude=None, rename=None, schema=None))]
    fn driver_plan(
        &self,
        tables: Option<Vec<String>>,
        exclude: Option<Vec<String>>,
        rename: Option<Vec<TableRename>>,
        schema: Option<String>,
    ) -> PyResult<DriverPlan> {
        let driver_plan_options_arg = DriverPlanOptions {
            tables,
            exclude,
            rename,
            schema,
        };

        Ok(DriverPlan {
            stream: self
                .core
                .driver_plan(Some(driver_plan_options_arg))
                .map_err(err)?,
        })
    }
    /// Reconstruct a git repo from a store (needs objects: true at sink time). Returns commits rebuilt.
    #[pyo3(signature = (source, dest, out, schema=None))]
    fn rebuild(
        &self,
        py: Python<'_>,
        source: String,
        dest: String,
        out: String,
        schema: Option<String>,
    ) -> PyResult<i64> {
        let rebuild_options_arg = RebuildOptions {
            source,
            dest,
            out,
            schema,
        };

        let core = self.core.clone();
        py.detach(move || core.rebuild(rebuild_options_arg))
            .map_err(err)
    }
    // @manual: watch — hand-written in lib.rs if this binding offers it.
}

/// Register every generated class + function on the `#[pymodule]`.
pub(crate) fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<SinkTarget>()?;
    m.add_class::<GitStats>()?;
    m.add_class::<GithubStats>()?;
    m.add_class::<SinkStats>()?;
    m.add_class::<FileDiff>()?;
    m.add_class::<ChangeBatch>()?;
    m.add_class::<Statement>()?;
    m.add_class::<TableRename>()?;
    m.add_class::<SinkOptions>()?;
    m.add_class::<ExtractOptions>()?;
    m.add_class::<RebuildOptions>()?;
    m.add_class::<ChangesOptions>()?;
    m.add_class::<DriverPlanOptions>()?;
    m.add_class::<Changes>()?;
    m.add_class::<DriverPlan>()?;
    m.add_class::<Entl>()?;
    m.add_function(wrap_pyfunction!(diff_commits, m)?)?;
    m.add_function(wrap_pyfunction!(file_at, m)?)?;
    m.add_function(wrap_pyfunction!(branch_exists, m)?)?;
    m.add_function(wrap_pyfunction!(current_branch, m)?)?;
    m.add_function(wrap_pyfunction!(commit_bodies, m)?)?;
    m.add_function(wrap_pyfunction!(ls_remote_heads, m)?)?;
    Ok(())
}
