//! GENERATED by fluessig bindgen from crates/fluessig/entl.tsp (api layer). Do not edit.
//! Regenerate: `bun run gen` in crates/entl-node. Hand-written half: crate::core_impl.
//! Ruby surface notes: options bags are flattened to trailing OPTIONAL POSITIONAL args
//! (kwargs are a follow-up); enum params are lowercase strings; input-model fields
//! (e.g. sink's `rename`) are not exposed yet.
//! straitjacket-allow-file:duplication — generated code repeats by design.
#![allow(clippy::all)]

use magnus::{function, method, prelude::*, Error, Ruby};
use std::sync::Arc;
use std::time::Duration;

fn rberr(e: impl std::fmt::Display) -> Error {
    let ruby = magnus::Ruby::get().expect("entl called outside the Ruby GVL");
    Error::new(ruby.exception_runtime_error(), e.to_string())
}

/// One poll result from a core stream (the sync primitive every stream shape dresses).
pub enum Poll<T> {
    Item(T),
    Idle,
    Closed,
}

/// The one sync primitive: a blocking, timeout-bounded poll.
pub trait PollStream<T>: Send + Sync {
    fn poll(&self, timeout: Duration) -> Poll<T>;
}

/// Bulk bytes cross into Ruby as a binary String (via magnus's `bytes` feature).
pub type Bytes = bytes::Bytes;

#[derive(Clone, Copy, PartialEq)]
pub enum SinkTarget {
    Sqlite,
    Jsonl,
    Postgres,
}
impl SinkTarget {
    pub fn parse(s: &str) -> anyhow::Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "sqlite" => Ok(Self::Sqlite),
            "jsonl" => Ok(Self::Jsonl),
            "postgres" => Ok(Self::Postgres),
            other => Err(anyhow::anyhow!(
                "unknown SinkTarget: {other} (expected sqlite | jsonl | postgres)"
            )),
        }
    }
}

/// What one git load produced.
#[magnus::wrap(class = "Entl::GitStats", free_immediately, size)]
#[derive(Clone)]
pub struct GitStats {
    pub new_commits: i64,
    pub file_changes: i64,
    pub refs: i64,
}
impl GitStats {
    fn get_new_commits(&self) -> i64 {
        self.new_commits.clone()
    }
    fn get_file_changes(&self) -> i64 {
        self.file_changes.clone()
    }
    fn get_refs(&self) -> i64 {
        self.refs.clone()
    }
}

/// What one GitHub load produced.
#[magnus::wrap(class = "Entl::GithubStats", free_immediately, size)]
#[derive(Clone)]
pub struct GithubStats {
    pub events: i64,
    pub pull_requests: i64,
    pub reviews: i64,
    pub review_comments: i64,
    pub issues: i64,
    pub comments: i64,
    pub workflow_runs: i64,
    pub check_runs: i64,
    pub users: i64,
}
impl GithubStats {
    fn get_events(&self) -> i64 {
        self.events.clone()
    }
    fn get_pull_requests(&self) -> i64 {
        self.pull_requests.clone()
    }
    fn get_reviews(&self) -> i64 {
        self.reviews.clone()
    }
    fn get_review_comments(&self) -> i64 {
        self.review_comments.clone()
    }
    fn get_issues(&self) -> i64 {
        self.issues.clone()
    }
    fn get_comments(&self) -> i64 {
        self.comments.clone()
    }
    fn get_workflow_runs(&self) -> i64 {
        self.workflow_runs.clone()
    }
    fn get_check_runs(&self) -> i64 {
        self.check_runs.clone()
    }
    fn get_users(&self) -> i64 {
        self.users.clone()
    }
}

/// What a sink() cycle produced: git + forge counts, and rows applied to the target.
#[magnus::wrap(class = "Entl::SinkStats", free_immediately, size)]
#[derive(Clone)]
pub struct SinkStats {
    pub new_commits: i64,
    pub file_changes: i64,
    pub refs: i64,
    pub pull_requests: i64,
    pub issues: i64,
    pub events: i64,
    pub workflow_runs: i64,
    pub check_runs: i64,
    pub rows: i64,
}
impl SinkStats {
    fn get_new_commits(&self) -> i64 {
        self.new_commits.clone()
    }
    fn get_file_changes(&self) -> i64 {
        self.file_changes.clone()
    }
    fn get_refs(&self) -> i64 {
        self.refs.clone()
    }
    fn get_pull_requests(&self) -> i64 {
        self.pull_requests.clone()
    }
    fn get_issues(&self) -> i64 {
        self.issues.clone()
    }
    fn get_events(&self) -> i64 {
        self.events.clone()
    }
    fn get_workflow_runs(&self) -> i64 {
        self.workflow_runs.clone()
    }
    fn get_check_runs(&self) -> i64 {
        self.check_runs.clone()
    }
    fn get_rows(&self) -> i64 {
        self.rows.clone()
    }
}

/// One changed file between two commits.
#[magnus::wrap(class = "Entl::FileDiff", free_immediately, size)]
#[derive(Clone)]
pub struct FileDiff {
    pub path: String,
    pub old_path: Option<String>,
    pub status: String,
    pub additions: i64,
    pub deletions: i64,
    pub patch: String,
}
impl FileDiff {
    fn get_path(&self) -> String {
        self.path.clone()
    }
    fn get_old_path(&self) -> Option<String> {
        self.old_path.clone()
    }
    fn get_status(&self) -> String {
        self.status.clone()
    }
    fn get_additions(&self) -> i64 {
        self.additions.clone()
    }
    fn get_deletions(&self) -> i64 {
        self.deletions.clone()
    }
    fn get_patch(&self) -> String {
        self.patch.clone()
    }
}

/// One change-stream batch. The rows stay columnar (Arrow): `ipc` yields them as
/// one Arrow IPC stream (a single RecordBatch, schema included), and the Python
/// class additionally speaks the Arrow PyCapsule protocol for zero-copy import
/// (`pa.record_batch(batch)`). Values are native Arrow types — oids are Binary,
/// timestamps Timestamp(µs) — unlike query()/extract()'s canonical JSON (hex
/// oids, RFC3339). No per-row `_op`: `op`/`table` ride this envelope.
#[magnus::wrap(class = "Entl::ChangeBatch", free_immediately, size)]
#[derive(Clone)]
pub struct ChangeBatch {
    pub(crate) table: String,
    pub(crate) op: String,
    // the rows, still columnar — encoded only when the getter is hit
    pub(crate) batch: entl_core::RecordBatch,
}
impl ChangeBatch {
    fn get_table(&self) -> String {
        self.table.clone()
    }
    fn get_op(&self) -> String {
        self.op.clone()
    }
    /// The rows as one Arrow IPC stream, as a binary String (red-arrow decodes it).
    fn get_ipc(&self) -> Result<Bytes, Error> {
        Ok(Bytes::from(
            entl_core::batch_ipc(&self.batch).map_err(rberr)?,
        ))
    }
}

/// One driver-plan statement: the host runs it verbatim against its own client.
#[magnus::wrap(class = "Entl::Statement", free_immediately, size)]
#[derive(Clone)]
pub struct Statement {
    pub sql: String,
    pub params: String,
    pub table: Option<String>,
}
impl Statement {
    fn get_sql(&self) -> String {
        self.sql.clone()
    }
    fn get_params(&self) -> String {
        self.params.clone()
    }
    fn get_table(&self) -> Option<String> {
        self.table.clone()
    }
}

#[derive(Clone)]
pub struct TableRename {
    pub from: String,
    pub to: String,
}

#[derive(Clone)]
pub struct SinkOptions {
    pub target: SinkTarget,
    pub path: Option<String>,
    pub github: Option<bool>,
    pub tables: Option<Vec<String>>,
    pub exclude: Option<Vec<String>>,
    pub rename: Option<Vec<TableRename>>,
    pub schema: Option<String>,
    pub objects: Option<bool>,
}

#[derive(Clone)]
pub struct ExtractOptions {
    pub source: String,
    pub path: String,
    pub tables: Option<Vec<String>>,
    pub schema: Option<String>,
}

#[derive(Clone)]
pub struct RebuildOptions {
    pub source: String,
    pub dest: String,
    pub out: String,
    pub schema: Option<String>,
}

#[derive(Clone)]
pub struct ChangesOptions {
    pub github: Option<bool>,
    pub objects: Option<bool>,
}

#[derive(Clone)]
pub struct DriverPlanOptions {
    pub tables: Option<Vec<String>>,
    pub exclude: Option<Vec<String>>,
    pub rename: Option<Vec<TableRename>>,
    pub schema: Option<String>,
}

/// The `Git` contract — implement over the engine in `crate::core_impl`.
pub trait GitCore: Sized + Send + Sync + 'static {
    fn diff_commits(
        repo_path: String,
        base: String,
        head: String,
        three_dot: bool,
    ) -> anyhow::Result<Vec<FileDiff>>;
    fn file_at(repo_path: String, commit: String, path: String) -> anyhow::Result<Option<String>>;
    fn branch_exists(repo_path: String, name: String) -> anyhow::Result<bool>;
    fn current_branch(repo_path: String) -> anyhow::Result<String>;
    fn commit_bodies(repo_path: String, branch: String) -> anyhow::Result<String>;
    fn ls_remote_heads(repo_path: String, pattern: String) -> anyhow::Result<Vec<String>>;
}

/// The `Entl` contract — implement over the engine in `crate::core_impl`.
pub trait EntlCore: Sized + Send + Sync + 'static {
    fn open(db_path: String) -> anyhow::Result<Self>;
    fn load_git(&self, repo_path: String) -> anyhow::Result<GitStats>;
    fn load_github(&self, repo_path: String) -> anyhow::Result<GithubStats>;
    fn query(&self, sql: String) -> anyhow::Result<String>;
    fn query_arrow(&self, sql: String) -> anyhow::Result<Bytes>;
    fn sink(&self, repo_path: String, options: SinkOptions) -> anyhow::Result<SinkStats>;
    fn extract(&self, options: ExtractOptions) -> anyhow::Result<String>;
    fn changes(
        &self,
        repo_path: String,
        options: Option<ChangesOptions>,
    ) -> anyhow::Result<Box<dyn PollStream<ChangeBatch>>>;
    fn driver_plan(
        &self,
        options: Option<DriverPlanOptions>,
    ) -> anyhow::Result<Box<dyn PollStream<Statement>>>;
    fn rebuild(&self, options: RebuildOptions) -> anyhow::Result<i64>;
}

/// Diff two commits (`base...head` when threeDot).
fn diff_commits(
    repo_path: String,
    base: String,
    head: String,
    three_dot: bool,
) -> Result<magnus::RArray, Error> {
    let out =
        <crate::core_impl::GitImpl as GitCore>::diff_commits(repo_path, base, head, three_dot)
            .map_err(rberr)?;
    let ruby = Ruby::get().map_err(|e| rberr(e))?;
    let ary = ruby.ary_new();
    for v in out {
        ary.push(v)?;
    }
    Ok(ary)
}

/// A file's content at a commit — null when absent or binary.
fn file_at(repo_path: String, commit: String, path: String) -> Result<Option<String>, Error> {
    <crate::core_impl::GitImpl as GitCore>::file_at(repo_path, commit, path).map_err(rberr)
}

fn branch_exists(repo_path: String, name: String) -> Result<bool, Error> {
    <crate::core_impl::GitImpl as GitCore>::branch_exists(repo_path, name).map_err(rberr)
}

fn current_branch(repo_path: String) -> Result<String, Error> {
    <crate::core_impl::GitImpl as GitCore>::current_branch(repo_path).map_err(rberr)
}

/// Commit subjects+bodies along a branch (JSON).
fn commit_bodies(repo_path: String, branch: String) -> Result<String, Error> {
    <crate::core_impl::GitImpl as GitCore>::commit_bodies(repo_path, branch).map_err(rberr)
}

/// Remote branch names matching a pattern (trailing-`*` glob). Fetches first.
fn ls_remote_heads(repo_path: String, pattern: String) -> Result<magnus::RArray, Error> {
    let out = <crate::core_impl::GitImpl as GitCore>::ls_remote_heads(repo_path, pattern)
        .map_err(rberr)?;
    let ruby = Ruby::get().map_err(|e| rberr(e))?;
    let ary = ruby.ary_new();
    for v in out {
        ary.push(v)?;
    }
    Ok(ary)
}

/// Poll-based stream from `Entl.changes` — `.next` returns the next item or nil.
#[magnus::wrap(class = "Entl::Changes", free_immediately, size)]
pub struct Changes {
    stream: Box<dyn PollStream<ChangeBatch>>,
}
impl Changes {
    fn next(&self) -> Option<ChangeBatch> {
        loop {
            match self.stream.poll(Duration::from_millis(500)) {
                Poll::Item(v) => return Some(v),
                Poll::Idle => continue,
                Poll::Closed => return None, // nil ends iteration
            }
        }
    }
}

/// Poll-based stream from `Entl.driverPlan` — `.next` returns the next item or nil.
#[magnus::wrap(class = "Entl::DriverPlan", free_immediately, size)]
pub struct DriverPlan {
    stream: Box<dyn PollStream<Statement>>,
}
impl DriverPlan {
    fn next(&self) -> Option<Statement> {
        loop {
            match self.stream.poll(Duration::from_millis(500)) {
                Poll::Item(v) => return Some(v),
                Poll::Idle => continue,
                Poll::Closed => return None, // nil ends iteration
            }
        }
    }
}

/// An open entl database. Heavy ops are unary (off-thread in async hosts).
#[magnus::wrap(class = "Entl", free_immediately, size)]
pub struct Entl {
    core: Arc<crate::core_impl::EntlImpl>,
}

impl Entl {
    /// Open (or create) the .duckdb at `dbPath` and apply the schema.
    fn new(db_path: String) -> Result<Self, Error> {
        Ok(Self {
            core: Arc::new(<crate::core_impl::EntlImpl as EntlCore>::open(db_path).map_err(rberr)?),
        })
    }
    /// Load git history from `repoPath` (one-way, incremental).
    fn load_git(&self, repo_path: String) -> Result<GitStats, Error> {
        self.core.load_git(repo_path).map_err(rberr)
    }
    /// Load GitHub data (events/PRs/issues/Actions). Needs a token.
    fn load_github(&self, repo_path: String) -> Result<GithubStats, Error> {
        self.core.load_github(repo_path).map_err(rberr)
    }
    /// Run a SQL query; JSON rows back.
    fn query(&self, sql: String) -> Result<String, Error> {
        self.core.query(sql).map_err(rberr)
    }
    /// Run a SQL query; the result as one Arrow IPC stream (schema + all batches) —
    /// the dataframe on-ramp (pyarrow → pandas/polars, apache-arrow JS, red-arrow).
    fn query_arrow(&self, sql: String) -> Result<Bytes, Error> {
        self.core.query_arrow(sql).map_err(rberr)
    }
    /// Pull `repoPath` and sync it into a target store, in one call.
    fn sink(&self, args: &[magnus::Value]) -> Result<SinkStats, Error> {
        let a = magnus::scan_args::scan_args::<
            (String, String),
            (
                Option<String>,
                Option<bool>,
                Option<Vec<String>>,
                Option<Vec<String>>,
                Option<String>,
                Option<bool>,
            ),
            (),
            (),
            (),
            (),
        >(args)?;
        let (repo_path, target) = a.required;
        let (path, github, tables, exclude, schema, objects) = a.optional;
        let target = SinkTarget::parse(&target).map_err(rberr)?;
        let sink_options_arg = SinkOptions {
            target,
            path,
            github,
            tables,
            exclude,
            schema,
            objects,
            rename: None,
        };

        self.core.sink(repo_path, sink_options_arg).map_err(rberr)
    }
    /// Read a store back into canonical rows (JSON; oids hex, timestamps RFC3339).
    fn extract(&self, args: &[magnus::Value]) -> Result<String, Error> {
        let a = magnus::scan_args::scan_args::<
            (String, String),
            (Option<Vec<String>>, Option<String>),
            (),
            (),
            (),
            (),
        >(args)?;
        let (source, path) = a.required;
        let (tables, schema) = a.optional;
        let extract_options_arg = ExtractOptions {
            source,
            path,
            tables,
            schema,
        };

        self.core.extract(extract_options_arg).map_err(rberr)
    }
    /// Stream the change batches from one pull (the stream plane).
    fn changes(&self, args: &[magnus::Value]) -> Result<Changes, Error> {
        let a = magnus::scan_args::scan_args::<
            (String,),
            (Option<bool>, Option<bool>),
            (),
            (),
            (),
            (),
        >(args)?;
        let (repo_path,) = a.required;
        let (github, objects) = a.optional;
        let changes_options_arg = ChangesOptions { github, objects };

        Ok(Changes {
            stream: self
                .core
                .changes(repo_path, Some(changes_options_arg))
                .map_err(rberr)?,
        })
    }
    /// Backfill this store into a driver target: stream {sql, params} for the host to execute.
    fn driver_plan(&self, args: &[magnus::Value]) -> Result<DriverPlan, Error> {
        let a = magnus::scan_args::scan_args::<
            (),
            (Option<Vec<String>>, Option<Vec<String>>, Option<String>),
            (),
            (),
            (),
            (),
        >(args)?;
        let (tables, exclude, schema) = a.optional;
        let driver_plan_options_arg = DriverPlanOptions {
            tables,
            exclude,
            schema,
            rename: None,
        };

        Ok(DriverPlan {
            stream: self
                .core
                .driver_plan(Some(driver_plan_options_arg))
                .map_err(rberr)?,
        })
    }
    /// Reconstruct a git repo from a store (needs objects: true at sink time). Returns commits rebuilt.
    fn rebuild(&self, args: &[magnus::Value]) -> Result<i64, Error> {
        let a = magnus::scan_args::scan_args::<
            (String, String, String),
            (Option<String>,),
            (),
            (),
            (),
            (),
        >(args)?;
        let (source, dest, out) = a.required;
        let (schema,) = a.optional;
        let rebuild_options_arg = RebuildOptions {
            source,
            dest,
            out,
            schema,
        };

        self.core.rebuild(rebuild_options_arg).map_err(rberr)
    }
    // @manual: watch — hand-written in lib.rs if this binding offers it.
}

/// Register the Entl class + every generated method (called from #[magnus::init]).
pub fn register(ruby: &Ruby) -> Result<(), Error> {
    let class = ruby.define_class("Entl", ruby.class_object())?;
    let c = class.define_class("GitStats", ruby.class_object())?;
    c.define_method("new_commits", method!(GitStats::get_new_commits, 0))?;
    c.define_method("file_changes", method!(GitStats::get_file_changes, 0))?;
    c.define_method("refs", method!(GitStats::get_refs, 0))?;
    let c = class.define_class("GithubStats", ruby.class_object())?;
    c.define_method("events", method!(GithubStats::get_events, 0))?;
    c.define_method("pull_requests", method!(GithubStats::get_pull_requests, 0))?;
    c.define_method("reviews", method!(GithubStats::get_reviews, 0))?;
    c.define_method(
        "review_comments",
        method!(GithubStats::get_review_comments, 0),
    )?;
    c.define_method("issues", method!(GithubStats::get_issues, 0))?;
    c.define_method("comments", method!(GithubStats::get_comments, 0))?;
    c.define_method("workflow_runs", method!(GithubStats::get_workflow_runs, 0))?;
    c.define_method("check_runs", method!(GithubStats::get_check_runs, 0))?;
    c.define_method("users", method!(GithubStats::get_users, 0))?;
    let c = class.define_class("SinkStats", ruby.class_object())?;
    c.define_method("new_commits", method!(SinkStats::get_new_commits, 0))?;
    c.define_method("file_changes", method!(SinkStats::get_file_changes, 0))?;
    c.define_method("refs", method!(SinkStats::get_refs, 0))?;
    c.define_method("pull_requests", method!(SinkStats::get_pull_requests, 0))?;
    c.define_method("issues", method!(SinkStats::get_issues, 0))?;
    c.define_method("events", method!(SinkStats::get_events, 0))?;
    c.define_method("workflow_runs", method!(SinkStats::get_workflow_runs, 0))?;
    c.define_method("check_runs", method!(SinkStats::get_check_runs, 0))?;
    c.define_method("rows", method!(SinkStats::get_rows, 0))?;
    let c = class.define_class("FileDiff", ruby.class_object())?;
    c.define_method("path", method!(FileDiff::get_path, 0))?;
    c.define_method("old_path", method!(FileDiff::get_old_path, 0))?;
    c.define_method("status", method!(FileDiff::get_status, 0))?;
    c.define_method("additions", method!(FileDiff::get_additions, 0))?;
    c.define_method("deletions", method!(FileDiff::get_deletions, 0))?;
    c.define_method("patch", method!(FileDiff::get_patch, 0))?;
    let c = class.define_class("ChangeBatch", ruby.class_object())?;
    c.define_method("table", method!(ChangeBatch::get_table, 0))?;
    c.define_method("op", method!(ChangeBatch::get_op, 0))?;
    c.define_method("ipc", method!(ChangeBatch::get_ipc, 0))?;
    let c = class.define_class("Statement", ruby.class_object())?;
    c.define_method("sql", method!(Statement::get_sql, 0))?;
    c.define_method("params", method!(Statement::get_params, 0))?;
    c.define_method("table", method!(Statement::get_table, 0))?;
    class.define_singleton_method("diff_commits", function!(diff_commits, 4))?;
    class.define_singleton_method("file_at", function!(file_at, 3))?;
    class.define_singleton_method("branch_exists", function!(branch_exists, 2))?;
    class.define_singleton_method("current_branch", function!(current_branch, 1))?;
    class.define_singleton_method("commit_bodies", function!(commit_bodies, 2))?;
    class.define_singleton_method("ls_remote_heads", function!(ls_remote_heads, 2))?;
    let s = class.define_class("Changes", ruby.class_object())?;
    s.define_method("next", method!(Changes::next, 0))?;
    let s = class.define_class("DriverPlan", ruby.class_object())?;
    s.define_method("next", method!(DriverPlan::next, 0))?;
    class.define_singleton_method("new", function!(Entl::new, 1))?;
    class.define_method("load_git", method!(Entl::load_git, 1))?;
    class.define_method("load_github", method!(Entl::load_github, 1))?;
    class.define_method("query", method!(Entl::query, 1))?;
    class.define_method("query_arrow", method!(Entl::query_arrow, 1))?;
    class.define_method("sink", method!(Entl::sink, -1))?;
    class.define_method("extract", method!(Entl::extract, -1))?;
    class.define_method("changes", method!(Entl::changes, -1))?;
    class.define_method("driver_plan", method!(Entl::driver_plan, -1))?;
    class.define_method("rebuild", method!(Entl::rebuild, -1))?;
    Ok(())
}
