//! GENERATED by fluessig bindgen from crates/fluessig/entl.tsp (api layer). Do not edit.
//! Regenerate: `bun run gen` in crates/entl-node. Hand-written halves: crate::core_impl
//! (the trait impls over entl-core) and the @manual ops in lib.rs.
//! straitjacket-allow-file:duplication — generated code repeats by design.
#![allow(clippy::all)]

// The fixed prelude — generated code uses fully-qualified paths elsewhere.
use std::sync::Arc;
use std::time::Duration;
use napi::bindgen_prelude::{AsyncTask, Result};
use napi::{Env, Task};
use napi_derive::napi;

fn err(e: impl std::fmt::Display) -> napi::Error {
    napi::Error::from_reason(e.to_string())
}

/// One poll result from a core stream (the sync primitive every stream shape dresses).
pub enum Poll<T> {
    Item(T),
    Idle,
    Closed,
}

/// The one sync primitive: a blocking, timeout-bounded poll.
pub trait PollStream<T>: Send + Sync {
    fn poll(&self, timeout: Duration) -> Poll<T>;
}

#[napi]
#[derive(Clone, Copy)]
pub enum SinkTarget {
    Sqlite,
    Jsonl,
    Postgres,
}

/// What one git load produced.
#[napi(object)]
#[derive(Clone)]
pub struct GitStats {
    pub new_commits: i64,
    pub file_changes: i64,
    pub refs: i64,
}

/// What one GitHub load produced.
#[napi(object)]
#[derive(Clone)]
pub struct GithubStats {
    pub events: i64,
    pub pull_requests: i64,
    pub reviews: i64,
    pub review_comments: i64,
    pub issues: i64,
    pub comments: i64,
    pub workflow_runs: i64,
    pub check_runs: i64,
    pub users: i64,
}

/// What a sink() cycle produced: git + forge counts, and rows applied to the target.
#[napi(object)]
#[derive(Clone)]
pub struct SinkStats {
    pub new_commits: i64,
    pub file_changes: i64,
    pub refs: i64,
    pub pull_requests: i64,
    pub issues: i64,
    pub events: i64,
    pub workflow_runs: i64,
    pub check_runs: i64,
    pub rows: i64,
}

/// One changed file between two commits.
#[napi(object)]
#[derive(Clone)]
pub struct FileDiff {
    pub path: String,
    pub old_path: Option<String>,
    pub status: String,
    pub additions: i64,
    pub deletions: i64,
    pub patch: String,
}

/// One change-stream batch (rows as JSON until the Arrow C-FFI handoff lands).
#[napi(object)]
#[derive(Clone)]
pub struct ChangeBatch {
    pub table: String,
    pub op: String,
    pub rows_json: String,
}

/// One driver-plan statement: the host runs it verbatim against its own client.
#[napi(object)]
#[derive(Clone)]
pub struct Statement {
    pub sql: String,
    pub params: String,
    pub table: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct TableRename {
    pub from: String,
    pub to: String,
}

#[napi(object)]
#[derive(Clone)]
pub struct SinkOptions {
    pub target: SinkTarget,
    pub path: Option<String>,
    pub github: Option<bool>,
    pub tables: Option<Vec<String>>,
    pub exclude: Option<Vec<String>>,
    pub rename: Option<Vec<TableRename>>,
    pub schema: Option<String>,
    pub objects: Option<bool>,
}

#[napi(object)]
#[derive(Clone)]
pub struct ExtractOptions {
    pub source: String,
    pub path: String,
    pub tables: Option<Vec<String>>,
    pub schema: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct RebuildOptions {
    pub source: String,
    pub dest: String,
    pub out: String,
    pub schema: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct ChangesOptions {
    pub github: Option<bool>,
    pub objects: Option<bool>,
}

#[napi(object)]
#[derive(Clone)]
pub struct DriverPlanOptions {
    pub tables: Option<Vec<String>>,
    pub exclude: Option<Vec<String>>,
    pub rename: Option<Vec<TableRename>>,
    pub schema: Option<String>,
}

/// The `Git` contract — implement over the engine in `crate::core_impl`.
pub trait GitCore: Sized + Send + Sync + 'static {
    fn diff_commits(repo_path: String, base: String, head: String, three_dot: bool) -> anyhow::Result<Vec<FileDiff>>;
    fn file_at(repo_path: String, commit: String, path: String) -> anyhow::Result<Option<String>>;
    fn branch_exists(repo_path: String, name: String) -> anyhow::Result<bool>;
    fn current_branch(repo_path: String) -> anyhow::Result<String>;
    fn commit_bodies(repo_path: String, branch: String) -> anyhow::Result<String>;
    fn ls_remote_heads(repo_path: String, pattern: String) -> anyhow::Result<Vec<String>>;
}

/// The `Entl` contract — implement over the engine in `crate::core_impl`.
pub trait EntlCore: Sized + Send + Sync + 'static {
    fn open(db_path: String) -> anyhow::Result<Self>;
    fn load_git(&self, repo_path: String) -> anyhow::Result<GitStats>;
    fn load_github(&self, repo_path: String) -> anyhow::Result<GithubStats>;
    fn query(&self, sql: String) -> anyhow::Result<String>;
    fn sink(&self, repo_path: String, options: SinkOptions) -> anyhow::Result<SinkStats>;
    fn extract(&self, options: ExtractOptions) -> anyhow::Result<String>;
    fn changes(&self, repo_path: String, options: Option<ChangesOptions>) -> anyhow::Result<Box<dyn PollStream<ChangeBatch>>>;
    fn driver_plan(&self, options: Option<DriverPlanOptions>) -> anyhow::Result<Box<dyn PollStream<Statement>>>;
    fn rebuild(&self, options: RebuildOptions) -> anyhow::Result<i64>;
}

pub struct DiffCommitsTask {
    repo_path: String,
    base: String,
    head: String,
    three_dot: bool,
}
impl Task for DiffCommitsTask {
    type Output = Vec<FileDiff>;
    type JsValue = Vec<FileDiff>;
    fn compute(&mut self) -> Result<Self::Output> {
        <crate::core_impl::GitImpl as GitCore>::diff_commits(self.repo_path.clone(), self.base.clone(), self.head.clone(), self.three_dot.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct FileAtTask {
    repo_path: String,
    commit: String,
    path: String,
}
impl Task for FileAtTask {
    type Output = Option<String>;
    type JsValue = Option<String>;
    fn compute(&mut self) -> Result<Self::Output> {
        <crate::core_impl::GitImpl as GitCore>::file_at(self.repo_path.clone(), self.commit.clone(), self.path.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct BranchExistsTask {
    repo_path: String,
    name: String,
}
impl Task for BranchExistsTask {
    type Output = bool;
    type JsValue = bool;
    fn compute(&mut self) -> Result<Self::Output> {
        <crate::core_impl::GitImpl as GitCore>::branch_exists(self.repo_path.clone(), self.name.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct CurrentBranchTask {
    repo_path: String,
}
impl Task for CurrentBranchTask {
    type Output = String;
    type JsValue = String;
    fn compute(&mut self) -> Result<Self::Output> {
        <crate::core_impl::GitImpl as GitCore>::current_branch(self.repo_path.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct CommitBodiesTask {
    repo_path: String,
    branch: String,
}
impl Task for CommitBodiesTask {
    type Output = String;
    type JsValue = String;
    fn compute(&mut self) -> Result<Self::Output> {
        <crate::core_impl::GitImpl as GitCore>::commit_bodies(self.repo_path.clone(), self.branch.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct LsRemoteHeadsTask {
    repo_path: String,
    pattern: String,
}
impl Task for LsRemoteHeadsTask {
    type Output = Vec<String>;
    type JsValue = Vec<String>;
    fn compute(&mut self) -> Result<Self::Output> {
        <crate::core_impl::GitImpl as GitCore>::ls_remote_heads(self.repo_path.clone(), self.pattern.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

/// Diff two commits (`base...head` when threeDot).
#[napi(ts_return_type = "Promise<FileDiff[]>")]
pub fn diff_commits(repo_path: String, base: String, head: String, three_dot: bool) -> AsyncTask<DiffCommitsTask> {
    AsyncTask::new(DiffCommitsTask { repo_path, base, head, three_dot })
}

/// A file's content at a commit — null when absent or binary.
#[napi(ts_return_type = "Promise<string | null>")]
pub fn file_at(repo_path: String, commit: String, path: String) -> AsyncTask<FileAtTask> {
    AsyncTask::new(FileAtTask { repo_path, commit, path })
}

#[napi(ts_return_type = "Promise<boolean>")]
pub fn branch_exists(repo_path: String, name: String) -> AsyncTask<BranchExistsTask> {
    AsyncTask::new(BranchExistsTask { repo_path, name })
}

#[napi(ts_return_type = "Promise<string>")]
pub fn current_branch(repo_path: String) -> AsyncTask<CurrentBranchTask> {
    AsyncTask::new(CurrentBranchTask { repo_path })
}

/// Commit subjects+bodies along a branch (JSON).
#[napi(ts_return_type = "Promise<string>")]
pub fn commit_bodies(repo_path: String, branch: String) -> AsyncTask<CommitBodiesTask> {
    AsyncTask::new(CommitBodiesTask { repo_path, branch })
}

/// Remote branch names matching a pattern (trailing-`*` glob). Fetches first.
#[napi(ts_return_type = "Promise<string[]>")]
pub fn ls_remote_heads(repo_path: String, pattern: String) -> AsyncTask<LsRemoteHeadsTask> {
    AsyncTask::new(LsRemoteHeadsTask { repo_path, pattern })
}

/// Poll-based stream from `Entl.changes` — call `next()` until it resolves null.
#[napi]
pub struct Changes {
    stream: Arc<dyn PollStream<ChangeBatch>>,
}
pub struct NextChangesTask {
    stream: Arc<dyn PollStream<ChangeBatch>>,
}
impl Task for NextChangesTask {
    type Output = Option<ChangeBatch>;
    type JsValue = Option<ChangeBatch>;
    fn compute(&mut self) -> Result<Self::Output> {
        loop {
            match self.stream.poll(Duration::from_millis(500)) {
                Poll::Item(v) => return Ok(Some(v)),
                Poll::Idle => continue,
                Poll::Closed => return Ok(None),
            }
        }
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}
#[napi]
impl Changes {
    #[napi(ts_return_type = "Promise<ChangeBatch | null>")]
    pub fn next(&self) -> AsyncTask<NextChangesTask> {
        AsyncTask::new(NextChangesTask { stream: self.stream.clone() })
    }
}

/// Poll-based stream from `Entl.driverPlan` — call `next()` until it resolves null.
#[napi]
pub struct DriverPlan {
    stream: Arc<dyn PollStream<Statement>>,
}
pub struct NextDriverPlanTask {
    stream: Arc<dyn PollStream<Statement>>,
}
impl Task for NextDriverPlanTask {
    type Output = Option<Statement>;
    type JsValue = Option<Statement>;
    fn compute(&mut self) -> Result<Self::Output> {
        loop {
            match self.stream.poll(Duration::from_millis(500)) {
                Poll::Item(v) => return Ok(Some(v)),
                Poll::Idle => continue,
                Poll::Closed => return Ok(None),
            }
        }
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}
#[napi]
impl DriverPlan {
    #[napi(ts_return_type = "Promise<Statement | null>")]
    pub fn next(&self) -> AsyncTask<NextDriverPlanTask> {
        AsyncTask::new(NextDriverPlanTask { stream: self.stream.clone() })
    }
}

pub struct LoadGitTask {
    core: Arc<crate::core_impl::EntlImpl>,
    repo_path: String,
}
impl Task for LoadGitTask {
    type Output = GitStats;
    type JsValue = GitStats;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.load_git(self.repo_path.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct LoadGithubTask {
    core: Arc<crate::core_impl::EntlImpl>,
    repo_path: String,
}
impl Task for LoadGithubTask {
    type Output = GithubStats;
    type JsValue = GithubStats;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.load_github(self.repo_path.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct QueryTask {
    core: Arc<crate::core_impl::EntlImpl>,
    sql: String,
}
impl Task for QueryTask {
    type Output = String;
    type JsValue = String;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.query(self.sql.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct SinkTask {
    core: Arc<crate::core_impl::EntlImpl>,
    repo_path: String,
    options: SinkOptions,
}
impl Task for SinkTask {
    type Output = SinkStats;
    type JsValue = SinkStats;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.sink(self.repo_path.clone(), self.options.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct ExtractTask {
    core: Arc<crate::core_impl::EntlImpl>,
    options: ExtractOptions,
}
impl Task for ExtractTask {
    type Output = String;
    type JsValue = String;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.extract(self.options.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct RebuildTask {
    core: Arc<crate::core_impl::EntlImpl>,
    options: RebuildOptions,
}
impl Task for RebuildTask {
    type Output = i64;
    type JsValue = i64;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.rebuild(self.options.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

/// An open entl database. Heavy ops are unary (off-thread in async hosts).
#[napi]
pub struct Entl {
    // pub(crate): the @manual ops in lib.rs extend this class and need the core
    pub(crate) core: Arc<crate::core_impl::EntlImpl>,
}

#[napi]
impl Entl {
    /// Open (or create) the .duckdb at `dbPath` and apply the schema.
    #[napi(constructor)]
    pub fn new(db_path: String) -> Result<Self> {
        Ok(Self { core: Arc::new(<crate::core_impl::EntlImpl as EntlCore>::open(db_path).map_err(err)?) })
    }
    /// Load git history from `repoPath` (one-way, incremental).
    #[napi(ts_return_type = "Promise<GitStats>")]
    pub fn load_git(&self, repo_path: String) -> AsyncTask<LoadGitTask> {
        AsyncTask::new(LoadGitTask { core: self.core.clone(), repo_path })
    }
    /// Load GitHub data (events/PRs/issues/Actions). Needs a token.
    #[napi(ts_return_type = "Promise<GithubStats>")]
    pub fn load_github(&self, repo_path: String) -> AsyncTask<LoadGithubTask> {
        AsyncTask::new(LoadGithubTask { core: self.core.clone(), repo_path })
    }
    /// Run a SQL query; JSON rows back.
    #[napi(ts_return_type = "Promise<string>")]
    pub fn query(&self, sql: String) -> AsyncTask<QueryTask> {
        AsyncTask::new(QueryTask { core: self.core.clone(), sql })
    }
    /// Pull `repoPath` and sync it into a target store, in one call.
    #[napi(ts_return_type = "Promise<SinkStats>")]
    pub fn sink(&self, repo_path: String, options: SinkOptions) -> AsyncTask<SinkTask> {
        AsyncTask::new(SinkTask { core: self.core.clone(), repo_path, options })
    }
    /// Read a store back into canonical rows (JSON; oids hex, timestamps RFC3339).
    #[napi(ts_return_type = "Promise<string>")]
    pub fn extract(&self, options: ExtractOptions) -> AsyncTask<ExtractTask> {
        AsyncTask::new(ExtractTask { core: self.core.clone(), options })
    }
    /// Stream the change batches from one pull (the stream plane).
    #[napi]
    pub fn changes(&self, repo_path: String, options: Option<ChangesOptions>) -> Result<Changes> {
        Ok(Changes { stream: Arc::from(self.core.changes(repo_path, options).map_err(err)?) })
    }
    /// Backfill this store into a driver target: stream {sql, params} for the host to execute.
    #[napi]
    pub fn driver_plan(&self, options: Option<DriverPlanOptions>) -> Result<DriverPlan> {
        Ok(DriverPlan { stream: Arc::from(self.core.driver_plan(options).map_err(err)?) })
    }
    /// Reconstruct a git repo from a store (needs objects: true at sink time). Returns commits rebuilt.
    #[napi(ts_return_type = "Promise<number>")]
    pub fn rebuild(&self, options: RebuildOptions) -> AsyncTask<RebuildTask> {
        AsyncTask::new(RebuildTask { core: self.core.clone(), options })
    }
    // @manual: watch — hand-written in lib.rs.
}
