/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Sanity probe — confirms the native addon loaded and links entl-core. */
export declare function version(): string
/**
 * Diff two commits locally → `Promise<string>` (JSON array of per-file changes +
 * full unified patches). `threeDot` shifts the base to the merge-base (GitHub's
 * `base...head` PR diff). Runs off the JS thread.
 */
export declare function diffCommits(repoPath: string, base: string, head: string, threeDot: boolean): Promise<string>
/**
 * Full text of `path` at `commit` → `Promise<string | null>` (null if absent or
 * binary). Local; runs off the JS thread.
 */
export declare function fileAt(repoPath: string, commit: string, path: string): Promise<string | null>
/** Does `name` (or `origin/<name>`) resolve to a commit? Fetches first → `Promise<boolean>`. */
export declare function branchExists(repoPath: string, name: string): Promise<boolean>
/** The checked-out branch (HEAD's short name). Local read, no fetch → `Promise<string>`. */
export declare function currentBranch(repoPath: string): Promise<string>
/**
 * NUL-separated commit message bodies reachable from `branch` (∪ `origin/<branch>`).
 * Fetches first → `Promise<string>`.
 */
export declare function commitBodies(repoPath: string, branch: string): Promise<string>
/** Remote branch names matching `pattern` (trailing-`*` glob). Fetches first → `Promise<string[]>`. */
export declare function lsRemoteHeads(repoPath: string, pattern: string): Promise<string[]>
export interface GitStats {
  newCommits: number
  fileChanges: number
  refs: number
}
export interface GithubStats {
  events: number
  pullRequests: number
  reviews: number
  reviewComments: number
  issues: number
  comments: number
  workflowRuns: number
  checkRuns: number
  users: number
}
/** The payload passed to the `watch` callback after each sync cycle. */
export interface SyncStats {
  newCommits: number
  fileChanges: number
  events: number
  pullRequests: number
  issues: number
  workflowRuns: number
}
/** Handle to a running `watch` loop. Call `stop()` to end it. */
export declare class WatchHandle {
  /** Stop the watch loop (takes effect after the current cycle). */
  stop(): void
}
/** An open entl database. Heavy methods return Promises and run off the JS thread. */
export declare class Entl {
  /** Open (or create) the .duckdb at `dbPath` and apply migrations. */
  constructor(dbPath: string)
  /** Load git history from `repoPath` (one-way, incremental). → `Promise<GitStats>`. */
  loadGit(repoPath: string): Promise<GitStats>
  /** Load GitHub data (events/PRs/issues/Actions). → `Promise<GithubStats>`. */
  loadGithub(repoPath: string): Promise<GithubStats>
  /**
   * Run a SQL query → `Promise<string>` (JSON array of rows). Runs off-thread,
   * so a big query (Linux-kernel scale) never blocks the event loop.
   */
  query(sql: string): Promise<string>
  /**
   * Watch `repoPath`: on a background thread, every `intervalSecs`, `git fetch`
   * + load git + load GitHub into the DB, then call `onSync(stats)` so the JS
   * side can mirror into PGlite (whose `live` then drives realtime). Returns a
   * handle; call `.stop()` to end it. The first cycle runs immediately.
   */
  watch(repoPath: string, intervalSecs: number, onSync: (stats: SyncStats) => void): WatchHandle
}
