/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum SinkTarget {
  Sqlite = 0,
  Jsonl = 1,
  Postgres = 2
}
/** What one git load produced. */
export interface GitStats {
  newCommits: number
  fileChanges: number
  refs: number
}
/** What one GitHub load produced. */
export interface GithubStats {
  events: number
  pullRequests: number
  reviews: number
  reviewComments: number
  issues: number
  comments: number
  workflowRuns: number
  checkRuns: number
  users: number
}
/** What a sink() cycle produced: git + forge counts, and rows applied to the target. */
export interface SinkStats {
  newCommits: number
  fileChanges: number
  refs: number
  pullRequests: number
  issues: number
  events: number
  workflowRuns: number
  checkRuns: number
  rows: number
}
/** One changed file between two commits. */
export interface FileDiff {
  path: string
  oldPath?: string
  status: string
  additions: number
  deletions: number
  patch: string
}
/** One change-stream batch (rows as JSON until the Arrow C-FFI handoff lands). */
export interface ChangeBatch {
  table: string
  op: string
  rowsJson: string
}
/** One driver-plan statement: the host runs it verbatim against its own client. */
export interface Statement {
  sql: string
  params: string
  table?: string
}
export interface TableRename {
  from: string
  to: string
}
export interface SinkOptions {
  target: SinkTarget
  path?: string
  github?: boolean
  tables?: Array<string>
  exclude?: Array<string>
  rename?: Array<TableRename>
  schema?: string
  objects?: boolean
}
export interface ExtractOptions {
  source: string
  path: string
  tables?: Array<string>
  schema?: string
}
export interface RebuildOptions {
  source: string
  dest: string
  out: string
  schema?: string
}
export interface ChangesOptions {
  github?: boolean
  objects?: boolean
}
export interface DriverPlanOptions {
  tables?: Array<string>
  exclude?: Array<string>
  rename?: Array<TableRename>
  schema?: string
}
/** Diff two commits (`base...head` when threeDot). */
export declare function diffCommits(repoPath: string, base: string, head: string, threeDot: boolean): Promise<FileDiff[]>
/** A file's content at a commit — null when absent or binary. */
export declare function fileAt(repoPath: string, commit: string, path: string): Promise<string | null>
export declare function branchExists(repoPath: string, name: string): Promise<boolean>
export declare function currentBranch(repoPath: string): Promise<string>
/** Commit subjects+bodies along a branch (JSON). */
export declare function commitBodies(repoPath: string, branch: string): Promise<string>
/** Remote branch names matching a pattern (trailing-`*` glob). Fetches first. */
export declare function lsRemoteHeads(repoPath: string, pattern: string): Promise<string[]>
/** Sanity probe — confirms the native addon loaded and links entl-core. */
export declare function version(): string
export interface SyncStats {
  newCommits: number
  fileChanges: number
  events: number
  pullRequests: number
  issues: number
  workflowRuns: number
}
/** Poll-based stream from `Entl.changes` — call `next()` until it resolves null. */
export declare class Changes {
  next(): Promise<ChangeBatch | null>
}
/** Poll-based stream from `Entl.driverPlan` — call `next()` until it resolves null. */
export declare class DriverPlan {
  next(): Promise<Statement | null>
}
/** An open entl database. Heavy ops are unary (off-thread in async hosts). */
export declare class Entl {
  /** Open (or create) the .duckdb at `dbPath` and apply the schema. */
  constructor(dbPath: string)
  /** Load git history from `repoPath` (one-way, incremental). */
  loadGit(repoPath: string): Promise<GitStats>
  /** Load GitHub data (events/PRs/issues/Actions). Needs a token. */
  loadGithub(repoPath: string): Promise<GithubStats>
  /** Run a SQL query; JSON rows back. */
  query(sql: string): Promise<string>
  /** Pull `repoPath` and sync it into a target store, in one call. */
  sink(repoPath: string, options: SinkOptions): Promise<SinkStats>
  /** Read a store back into canonical rows (JSON; oids hex, timestamps RFC3339). */
  extract(options: ExtractOptions): Promise<string>
  /** Stream the change batches from one pull (the stream plane). */
  changes(repoPath: string, options?: ChangesOptions | undefined | null): Changes
  /** Backfill this store into a driver target: stream {sql, params} for the host to execute. */
  driverPlan(options?: DriverPlanOptions | undefined | null): DriverPlan
  /** Reconstruct a git repo from a store (needs objects: true at sink time). Returns commits rebuilt. */
  rebuild(options: RebuildOptions): Promise<number>
  /**
   * Watch `repoPath`: on a background thread, every `intervalSecs`, `git fetch`
   * + load git + load GitHub into the DB, then call `onSync(stats)` so the JS
   * side can mirror (e.g. into PGlite, whose `live` drives realtime). Returns a
   * handle; call `.stop()` to end it. The first cycle runs immediately.
   */
  watch(repoPath: string, intervalSecs: number, onSync: (stats: SyncStats) => void): WatchHandle
}
/** Handle to a running `watch` loop. Call `stop()` to end it. */
export declare class WatchHandle {
  /** Stop the watch loop (takes effect after the current cycle). */
  stop(): void
}
