/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Sanity probe — confirms the native addon loaded and links entl-core. */
export declare function version(): string
/**
 * Diff two commits locally → `Promise<string>` (JSON array of per-file changes +
 * full unified patches). `threeDot` shifts the base to the merge-base (GitHub's
 * `base...head` PR diff). Runs off the JS thread.
 */
export declare function diffCommits(repoPath: string, base: string, head: string, threeDot: boolean): Promise<string>
/**
 * Full text of `path` at `commit` → `Promise<string | null>` (null if absent or
 * binary). Local; runs off the JS thread.
 */
export declare function fileAt(repoPath: string, commit: string, path: string): Promise<string | null>
/** Does `name` (or `origin/<name>`) resolve to a commit? Fetches first → `Promise<boolean>`. */
export declare function branchExists(repoPath: string, name: string): Promise<boolean>
/** The checked-out branch (HEAD's short name). Local read, no fetch → `Promise<string>`. */
export declare function currentBranch(repoPath: string): Promise<string>
/**
 * NUL-separated commit message bodies reachable from `branch` (∪ `origin/<branch>`).
 * Fetches first → `Promise<string>`.
 */
export declare function commitBodies(repoPath: string, branch: string): Promise<string>
/** Remote branch names matching `pattern` (trailing-`*` glob). Fetches first → `Promise<string[]>`. */
export declare function lsRemoteHeads(repoPath: string, pattern: string): Promise<string[]>
export interface GitStats {
  newCommits: number
  fileChanges: number
  refs: number
}
export interface GithubStats {
  events: number
  pullRequests: number
  reviews: number
  reviewComments: number
  issues: number
  comments: number
  workflowRuns: number
  checkRuns: number
  users: number
}
/**
 * A built-in sink target. Regenerates as a TS `enum SinkTarget` — callers write
 * `SinkTarget.Sqlite`. Maps onto the source-of-truth [`entl_core::SinkTarget`].
 */
export const enum SinkTarget {
  Sqlite = 0,
  Jsonl = 1,
  Postgres = 2
}
/** Rename a table at the sink (`from` → `to`). */
export interface TableRename {
  from: string
  to: string
}
/** Options for `Entl.sink()`. */
export interface SinkOptions {
  /** Which target to write. */
  target: SinkTarget
  /** The SQLite file, the JSONL output directory, or the Postgres connection URL. */
  path?: string
  /** Also pull GitHub (default true). Requires a token (`gh auth token` / GH_TOKEN). */
  github?: boolean
  /** Only write these tables (default: all). */
  tables?: Array<string>
  /** Skip these tables. */
  exclude?: Array<string>
  /** Rename tables at the sink. */
  rename?: Array<TableRename>
  /** Target schema (Postgres only; default "entl"). */
  schema?: string
  /** Also store the object graph (trees/blobs + raw content) so the store can rebuild the repo. */
  objects?: boolean
}
/** What a `sink()` cycle produced: the git + forge counts, and rows applied to the target. */
export interface SinkStats {
  newCommits: number
  fileChanges: number
  refs: number
  pullRequests: number
  issues: number
  events: number
  workflowRuns: number
  checkRuns: number
  /** Total rows the sink applied across all change batches. */
  rows: number
}
/** Options for `Entl.extract()`. */
export interface ExtractOptions {
  /** Source store: `duckdb` | `sqlite` | `jsonl` | `postgres`. */
  source: string
  /** The store location (file / directory / Postgres URL). */
  path: string
  /** Which tables to read (default: the git tables). */
  tables?: Array<string>
  /** Postgres schema (default "entl"). */
  schema?: string
}
/** The payload passed to the `watch` callback after each sync cycle. */
export interface SyncStats {
  newCommits: number
  fileChanges: number
  events: number
  pullRequests: number
  issues: number
  workflowRuns: number
}
/** Handle to a running `watch` loop. Call `stop()` to end it. */
export declare class WatchHandle {
  /** Stop the watch loop (takes effect after the current cycle). */
  stop(): void
}
/** An open entl database. Heavy methods return Promises and run off the JS thread. */
export declare class Entl {
  /** Open (or create) the .duckdb at `dbPath` and apply migrations. */
  constructor(dbPath: string)
  /** Load git history from `repoPath` (one-way, incremental). → `Promise<GitStats>`. */
  loadGit(repoPath: string): Promise<GitStats>
  /** Load GitHub data (events/PRs/issues/Actions). → `Promise<GithubStats>`. */
  loadGithub(repoPath: string): Promise<GithubStats>
  /**
   * Run a SQL query → `Promise<string>` (JSON array of rows). Runs off-thread,
   * so a big query (Linux-kernel scale) never blocks the event loop.
   */
  query(sql: string): Promise<string>
  /**
   * Pull `repoPath` and sync it into `options.target` (SQLite file / JSONL dir), in one
   * call. Writes both this handle's DuckDB (the default store) and the chosen target. Runs
   * off the JS thread → `Promise<SinkStats>`.
   */
  sink(repoPath: string, options: SinkOptions): Promise<SinkStats>
  /**
   * Read a store back into canonical rows → `Promise<string>` (JSON: table → rows, normalized
   * like the sinks write — oids hex, timestamps RFC3339). The reverse of `sink`. Off the JS
   * thread.
   */
  extract(options: ExtractOptions): Promise<string>
  /**
   * Watch `repoPath`: on a background thread, every `intervalSecs`, `git fetch`
   * + load git + load GitHub into the DB, then call `onSync(stats)` so the JS
   * side can mirror into PGlite (whose `live` then drives realtime). Returns a
   * handle; call `.stop()` to end it. The first cycle runs immediately.
   */
  watch(repoPath: string, intervalSecs: number, onSync: (stats: SyncStats) => void): WatchHandle
}
