// Drizzle (pg-core) schema for entl's tables, as mirrored into Postgres/PGlite by
// `syncInto` (the `entl` schema). Import this for typed reads + joins against your
// own tables. The actual definitions are generated from entl's schema (single
// source of truth) — see `schema.gen.ts`, regenerated by `bun run gen`.

export * from "./schema.gen";
