//! GENERATED by fluessig from crates/fluessig/entl.tsp — DO NOT EDIT.
//!
//! The entl schema as code: per-dialect DDL templates (`__table__` is
//! substituted with the possibly-renamed target name, matching the sink
//! convention) + primary keys, lowered from the fluessig catalog. The
//! parity gate (fluessig tests/sql_parity.rs) holds these equal to the
//! hand-written migrations; the regenerates-identically test
//! (fluessig tests/entl_catalog.rs) holds this file equal to the catalog.
//!
//! Regenerate:
//!   cargo run -p fluessig --bin fluessig-gen -- \
//!     crates/fluessig/catalog.json crates/entl-core/src/schema_gen.rs

/// One table's schema, as code.
pub struct TableSchema {
    pub name: &'static str,
    pub pk: &'static [&'static str],
    pub ddl: &'static str,
}

/// The Postgres projection of every physical table in the catalog.
pub const PG_TABLES: &[TableSchema] = &[
    TableSchema { name: "blobs", pk: &["oid"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "oid" text PRIMARY KEY,
  "repo_id" text NOT NULL,
  "size" bigint NOT NULL,
  "is_binary" boolean DEFAULT false NOT NULL,
  "content_text" text,
  "content_sha" text,
  "content" text
);
"# },
    TableSchema { name: "commit_parents", pk: &["commit_oid", "idx"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "commit_oid" text NOT NULL,
  "idx" integer NOT NULL,
  "parent_oid" text NOT NULL,
  PRIMARY KEY ("commit_oid", "idx")
);
"# },
    TableSchema { name: "commits", pk: &["oid"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "oid" text PRIMARY KEY,
  "repo_id" text NOT NULL,
  "tree_oid" text NOT NULL,
  "message" text NOT NULL,
  "summary" text NOT NULL,
  "author_name" text,
  "author_email" text,
  "author_when" timestamptz,
  "author_tz" text,
  "committer_name" text,
  "committer_email" text,
  "committer_when" timestamptz,
  "committer_tz" text,
  "parent_count" integer DEFAULT 0 NOT NULL,
  "is_merge" boolean DEFAULT false NOT NULL,
  "gpg_signed" boolean DEFAULT false NOT NULL
);
"# },
    TableSchema { name: "conflicts", pk: &["repo_id", "merge_oid", "path"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "merge_oid" text NOT NULL,
  "path" text NOT NULL,
  "unresolved" boolean NOT NULL,
  PRIMARY KEY ("repo_id", "merge_oid", "path")
);
"# },
    TableSchema { name: "file_changes", pk: &["commit_oid", "path"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "commit_oid" text NOT NULL,
  "path" text NOT NULL,
  "old_path" text,
  "status" text NOT NULL,
  "additions" integer,
  "deletions" integer,
  "blob_oid" text,
  "old_blob_oid" text,
  PRIMARY KEY ("commit_oid", "path")
);
"# },
    TableSchema { name: "gh_assignees", pk: &["repo_id", "subject_type", "subject_number", "user_id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "subject_type" text NOT NULL,
  "subject_number" integer NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("repo_id", "subject_type", "subject_number", "user_id")
);
"# },
    TableSchema { name: "gh_check_runs", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "repo_id" text NOT NULL,
  "commit_oid" text,
  "name" text,
  "status" text,
  "conclusion" text,
  "started_at" timestamptz,
  "completed_at" timestamptz
);
"# },
    TableSchema { name: "gh_comments", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "subject_type" text NOT NULL,
  "repo_id" text NOT NULL,
  "subject_number" integer NOT NULL,
  "author_id" bigint,
  "body" text,
  "created_at" timestamptz
);
"# },
    TableSchema { name: "gh_commit_statuses", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "repo_id" text NOT NULL,
  "commit_oid" text NOT NULL,
  "context" text,
  "state" text,
  "description" text,
  "target_url" text,
  "created_at" timestamptz
);
"# },
    TableSchema { name: "gh_events", pk: &["repo_id", "id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "id" text NOT NULL,
  "type" text,
  "actor_id" bigint,
  "actor_login" text,
  "created_at" timestamptz,
  "payload" text,
  PRIMARY KEY ("repo_id", "id")
);
"# },
    TableSchema { name: "gh_issues", pk: &["repo_id", "number"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "number" integer NOT NULL,
  "title" text,
  "body" text,
  "state" text NOT NULL,
  "author_id" bigint,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "closed_at" timestamptz,
  PRIMARY KEY ("repo_id", "number")
);
"# },
    TableSchema { name: "gh_jobs", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "run_id" bigint NOT NULL,
  "name" text,
  "status" text,
  "conclusion" text,
  "started_at" timestamptz,
  "completed_at" timestamptz,
  "runner_name" text
);
"# },
    TableSchema { name: "gh_labeled", pk: &["repo_id", "subject_type", "subject_number", "label_name"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "subject_type" text NOT NULL,
  "subject_number" integer NOT NULL,
  "label_name" text NOT NULL,
  PRIMARY KEY ("repo_id", "subject_type", "subject_number", "label_name")
);
"# },
    TableSchema { name: "gh_labels", pk: &["repo_id", "name"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "name" text NOT NULL,
  "color" text,
  "description" text,
  PRIMARY KEY ("repo_id", "name")
);
"# },
    TableSchema { name: "gh_pr_commits", pk: &["repo_id", "pr_number", "commit_oid"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "pr_number" integer NOT NULL,
  "commit_oid" text NOT NULL,
  PRIMARY KEY ("repo_id", "pr_number", "commit_oid")
);
"# },
    TableSchema { name: "gh_pr_reviews", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "repo_id" text NOT NULL,
  "pr_number" integer NOT NULL,
  "reviewer_id" bigint,
  "state" text,
  "submitted_at" timestamptz,
  "body" text
);
"# },
    TableSchema { name: "gh_pull_requests", pk: &["repo_id", "number"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "number" integer NOT NULL,
  "title" text,
  "body" text,
  "state" text NOT NULL,
  "author_id" bigint,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "closed_at" timestamptz,
  "merged_at" timestamptz,
  "merge_commit_oid" text,
  "head_ref" text,
  "base_ref" text,
  "additions" integer,
  "deletions" integer,
  "changed_files" integer,
  "is_draft" boolean DEFAULT false NOT NULL,
  "mergeable" text,
  "checks" text,
  "head_oid" text,
  "base_oid" text,
  PRIMARY KEY ("repo_id", "number")
);
"# },
    TableSchema { name: "gh_requested_reviewers", pk: &["repo_id", "pr_number", "user_id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "pr_number" integer NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("repo_id", "pr_number", "user_id")
);
"# },
    TableSchema { name: "gh_review_comments", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "repo_id" text NOT NULL,
  "pr_number" integer NOT NULL,
  "path" text,
  "line" integer,
  "side" text,
  "commit_oid" text,
  "author_id" bigint,
  "body" text,
  "created_at" timestamptz,
  "in_reply_to" bigint
);
"# },
    TableSchema { name: "gh_steps", pk: &["job_id", "number"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "job_id" bigint NOT NULL,
  "number" integer NOT NULL,
  "name" text,
  "status" text,
  "conclusion" text,
  "started_at" timestamptz,
  "completed_at" timestamptz,
  PRIMARY KEY ("job_id", "number")
);
"# },
    TableSchema { name: "gh_users", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "login" text NOT NULL,
  "type" text,
  "name" text
);
"# },
    TableSchema { name: "gh_workflow_runs", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "repo_id" text NOT NULL,
  "workflow_id" bigint,
  "head_oid" text,
  "head_branch" text,
  "event" text,
  "status" text,
  "conclusion" text,
  "run_number" integer,
  "run_attempt" integer,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "run_started_at" timestamptz
);
"# },
    TableSchema { name: "gh_workflows", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "repo_id" text NOT NULL,
  "name" text,
  "path" text,
  "state" text
);
"# },
    TableSchema { name: "refs", pk: &["repo_id", "name"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "name" text NOT NULL,
  "kind" text NOT NULL,
  "target_oid" text NOT NULL,
  "is_symbolic" boolean DEFAULT false NOT NULL,
  "upstream" text,
  PRIMARY KEY ("repo_id", "name")
);
"# },
    TableSchema { name: "repos", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" text PRIMARY KEY,
  "path" text NOT NULL,
  "remote_url" text,
  "host" text,
  "owner" text,
  "name" text,
  "default_branch" text,
  "first_synced_at" timestamptz,
  "last_synced_at" timestamptz
);
"# },
    TableSchema { name: "sync_state", pk: &["resource"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "resource" text PRIMARY KEY,
  "cursor" text,
  "etag" text,
  "watermark" timestamptz,
  "last_synced_at" timestamptz,
  "last_error" text
);
"# },
    TableSchema { name: "tree_entries", pk: &["tree_oid", "name"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "tree_oid" text NOT NULL,
  "name" text NOT NULL,
  "path" text NOT NULL,
  "mode" text NOT NULL,
  "entry_type" text NOT NULL,
  "child_oid" text NOT NULL,
  PRIMARY KEY ("tree_oid", "name")
);
"# },
    TableSchema { name: "trees", pk: &["oid"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "oid" text PRIMARY KEY,
  "repo_id" text NOT NULL
);
"# },
];

/// The Sqlite projection of every physical table in the catalog.
pub const SQLITE_TABLES: &[TableSchema] = &[
    TableSchema { name: "blobs", pk: &["oid"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "oid" text PRIMARY KEY,
  "repo_id" text NOT NULL,
  "size" integer NOT NULL,
  "is_binary" integer DEFAULT false NOT NULL,
  "content_text" text,
  "content_sha" text,
  "content" text
);
"# },
    TableSchema { name: "commit_parents", pk: &["commit_oid", "idx"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "commit_oid" text NOT NULL,
  "idx" integer NOT NULL,
  "parent_oid" text NOT NULL,
  PRIMARY KEY ("commit_oid", "idx")
);
"# },
    TableSchema { name: "commits", pk: &["oid"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "oid" text PRIMARY KEY,
  "repo_id" text NOT NULL,
  "tree_oid" text NOT NULL,
  "message" text NOT NULL,
  "summary" text NOT NULL,
  "author_name" text,
  "author_email" text,
  "author_when" text,
  "author_tz" text,
  "committer_name" text,
  "committer_email" text,
  "committer_when" text,
  "committer_tz" text,
  "parent_count" integer DEFAULT 0 NOT NULL,
  "is_merge" integer DEFAULT false NOT NULL,
  "gpg_signed" integer DEFAULT false NOT NULL
);
"# },
    TableSchema { name: "conflicts", pk: &["repo_id", "merge_oid", "path"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "merge_oid" text NOT NULL,
  "path" text NOT NULL,
  "unresolved" integer NOT NULL,
  PRIMARY KEY ("repo_id", "merge_oid", "path")
);
"# },
    TableSchema { name: "file_changes", pk: &["commit_oid", "path"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "commit_oid" text NOT NULL,
  "path" text NOT NULL,
  "old_path" text,
  "status" text NOT NULL,
  "additions" integer,
  "deletions" integer,
  "blob_oid" text,
  "old_blob_oid" text,
  PRIMARY KEY ("commit_oid", "path")
);
"# },
    TableSchema { name: "gh_assignees", pk: &["repo_id", "subject_type", "subject_number", "user_id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "subject_type" text NOT NULL,
  "subject_number" integer NOT NULL,
  "user_id" integer NOT NULL,
  PRIMARY KEY ("repo_id", "subject_type", "subject_number", "user_id")
);
"# },
    TableSchema { name: "gh_check_runs", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" integer PRIMARY KEY,
  "repo_id" text NOT NULL,
  "commit_oid" text,
  "name" text,
  "status" text,
  "conclusion" text,
  "started_at" text,
  "completed_at" text
);
"# },
    TableSchema { name: "gh_comments", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" integer PRIMARY KEY,
  "subject_type" text NOT NULL,
  "repo_id" text NOT NULL,
  "subject_number" integer NOT NULL,
  "author_id" integer,
  "body" text,
  "created_at" text
);
"# },
    TableSchema { name: "gh_commit_statuses", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" integer PRIMARY KEY,
  "repo_id" text NOT NULL,
  "commit_oid" text NOT NULL,
  "context" text,
  "state" text,
  "description" text,
  "target_url" text,
  "created_at" text
);
"# },
    TableSchema { name: "gh_events", pk: &["repo_id", "id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "id" text NOT NULL,
  "type" text,
  "actor_id" integer,
  "actor_login" text,
  "created_at" text,
  "payload" text,
  PRIMARY KEY ("repo_id", "id")
);
"# },
    TableSchema { name: "gh_issues", pk: &["repo_id", "number"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "number" integer NOT NULL,
  "title" text,
  "body" text,
  "state" text NOT NULL,
  "author_id" integer,
  "created_at" text,
  "updated_at" text,
  "closed_at" text,
  PRIMARY KEY ("repo_id", "number")
);
"# },
    TableSchema { name: "gh_jobs", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" integer PRIMARY KEY,
  "run_id" integer NOT NULL,
  "name" text,
  "status" text,
  "conclusion" text,
  "started_at" text,
  "completed_at" text,
  "runner_name" text
);
"# },
    TableSchema { name: "gh_labeled", pk: &["repo_id", "subject_type", "subject_number", "label_name"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "subject_type" text NOT NULL,
  "subject_number" integer NOT NULL,
  "label_name" text NOT NULL,
  PRIMARY KEY ("repo_id", "subject_type", "subject_number", "label_name")
);
"# },
    TableSchema { name: "gh_labels", pk: &["repo_id", "name"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "name" text NOT NULL,
  "color" text,
  "description" text,
  PRIMARY KEY ("repo_id", "name")
);
"# },
    TableSchema { name: "gh_pr_commits", pk: &["repo_id", "pr_number", "commit_oid"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "pr_number" integer NOT NULL,
  "commit_oid" text NOT NULL,
  PRIMARY KEY ("repo_id", "pr_number", "commit_oid")
);
"# },
    TableSchema { name: "gh_pr_reviews", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" integer PRIMARY KEY,
  "repo_id" text NOT NULL,
  "pr_number" integer NOT NULL,
  "reviewer_id" integer,
  "state" text,
  "submitted_at" text,
  "body" text
);
"# },
    TableSchema { name: "gh_pull_requests", pk: &["repo_id", "number"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "number" integer NOT NULL,
  "title" text,
  "body" text,
  "state" text NOT NULL,
  "author_id" integer,
  "created_at" text,
  "updated_at" text,
  "closed_at" text,
  "merged_at" text,
  "merge_commit_oid" text,
  "head_ref" text,
  "base_ref" text,
  "additions" integer,
  "deletions" integer,
  "changed_files" integer,
  "is_draft" integer DEFAULT false NOT NULL,
  "mergeable" text,
  "checks" text,
  "head_oid" text,
  "base_oid" text,
  PRIMARY KEY ("repo_id", "number")
);
"# },
    TableSchema { name: "gh_requested_reviewers", pk: &["repo_id", "pr_number", "user_id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "pr_number" integer NOT NULL,
  "user_id" integer NOT NULL,
  PRIMARY KEY ("repo_id", "pr_number", "user_id")
);
"# },
    TableSchema { name: "gh_review_comments", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" integer PRIMARY KEY,
  "repo_id" text NOT NULL,
  "pr_number" integer NOT NULL,
  "path" text,
  "line" integer,
  "side" text,
  "commit_oid" text,
  "author_id" integer,
  "body" text,
  "created_at" text,
  "in_reply_to" integer
);
"# },
    TableSchema { name: "gh_steps", pk: &["job_id", "number"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "job_id" integer NOT NULL,
  "number" integer NOT NULL,
  "name" text,
  "status" text,
  "conclusion" text,
  "started_at" text,
  "completed_at" text,
  PRIMARY KEY ("job_id", "number")
);
"# },
    TableSchema { name: "gh_users", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" integer PRIMARY KEY,
  "login" text NOT NULL,
  "type" text,
  "name" text
);
"# },
    TableSchema { name: "gh_workflow_runs", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" integer PRIMARY KEY,
  "repo_id" text NOT NULL,
  "workflow_id" integer,
  "head_oid" text,
  "head_branch" text,
  "event" text,
  "status" text,
  "conclusion" text,
  "run_number" integer,
  "run_attempt" integer,
  "created_at" text,
  "updated_at" text,
  "run_started_at" text
);
"# },
    TableSchema { name: "gh_workflows", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" integer PRIMARY KEY,
  "repo_id" text NOT NULL,
  "name" text,
  "path" text,
  "state" text
);
"# },
    TableSchema { name: "refs", pk: &["repo_id", "name"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "name" text NOT NULL,
  "kind" text NOT NULL,
  "target_oid" text NOT NULL,
  "is_symbolic" integer DEFAULT false NOT NULL,
  "upstream" text,
  PRIMARY KEY ("repo_id", "name")
);
"# },
    TableSchema { name: "repos", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" text PRIMARY KEY,
  "path" text NOT NULL,
  "remote_url" text,
  "host" text,
  "owner" text,
  "name" text,
  "default_branch" text,
  "first_synced_at" text,
  "last_synced_at" text
);
"# },
    TableSchema { name: "sync_state", pk: &["resource"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "resource" text PRIMARY KEY,
  "cursor" text,
  "etag" text,
  "watermark" text,
  "last_synced_at" text,
  "last_error" text
);
"# },
    TableSchema { name: "tree_entries", pk: &["tree_oid", "name"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "tree_oid" text NOT NULL,
  "name" text NOT NULL,
  "path" text NOT NULL,
  "mode" text NOT NULL,
  "entry_type" text NOT NULL,
  "child_oid" text NOT NULL,
  PRIMARY KEY ("tree_oid", "name")
);
"# },
    TableSchema { name: "trees", pk: &["oid"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "oid" text PRIMARY KEY,
  "repo_id" text NOT NULL
);
"# },
];

/// The Duckdb projection of every physical table in the catalog.
pub const DUCKDB_TABLES: &[TableSchema] = &[
    TableSchema { name: "blobs", pk: &["oid"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "oid" blob PRIMARY KEY,
  "repo_id" text NOT NULL,
  "size" bigint NOT NULL,
  "is_binary" boolean DEFAULT false NOT NULL,
  "content_text" text,
  "content_sha" text,
  "content" blob
);
"# },
    TableSchema { name: "commit_parents", pk: &["commit_oid", "idx"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "commit_oid" blob NOT NULL,
  "idx" integer NOT NULL,
  "parent_oid" blob NOT NULL,
  PRIMARY KEY ("commit_oid", "idx")
);
"# },
    TableSchema { name: "commits", pk: &["oid"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "oid" blob PRIMARY KEY,
  "repo_id" text NOT NULL,
  "tree_oid" blob NOT NULL,
  "message" text NOT NULL,
  "summary" text NOT NULL,
  "author_name" text,
  "author_email" text,
  "author_when" timestamp,
  "author_tz" text,
  "committer_name" text,
  "committer_email" text,
  "committer_when" timestamp,
  "committer_tz" text,
  "parent_count" integer DEFAULT 0 NOT NULL,
  "is_merge" boolean DEFAULT false NOT NULL,
  "gpg_signed" boolean DEFAULT false NOT NULL
);
"# },
    TableSchema { name: "conflicts", pk: &["repo_id", "merge_oid", "path"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "merge_oid" text NOT NULL,
  "path" text NOT NULL,
  "unresolved" boolean NOT NULL,
  PRIMARY KEY ("repo_id", "merge_oid", "path")
);
"# },
    TableSchema { name: "file_changes", pk: &["commit_oid", "path"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "commit_oid" blob NOT NULL,
  "path" text NOT NULL,
  "old_path" text,
  "status" text NOT NULL,
  "additions" integer,
  "deletions" integer,
  "blob_oid" blob,
  "old_blob_oid" blob,
  PRIMARY KEY ("commit_oid", "path")
);
"# },
    TableSchema { name: "gh_assignees", pk: &["repo_id", "subject_type", "subject_number", "user_id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "subject_type" text NOT NULL,
  "subject_number" integer NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("repo_id", "subject_type", "subject_number", "user_id")
);
"# },
    TableSchema { name: "gh_check_runs", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "repo_id" text NOT NULL,
  "commit_oid" blob,
  "name" text,
  "status" text,
  "conclusion" text,
  "started_at" timestamp,
  "completed_at" timestamp
);
"# },
    TableSchema { name: "gh_comments", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "subject_type" text NOT NULL,
  "repo_id" text NOT NULL,
  "subject_number" integer NOT NULL,
  "author_id" bigint,
  "body" text,
  "created_at" timestamp
);
"# },
    TableSchema { name: "gh_commit_statuses", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "repo_id" text NOT NULL,
  "commit_oid" blob NOT NULL,
  "context" text,
  "state" text,
  "description" text,
  "target_url" text,
  "created_at" timestamp
);
"# },
    TableSchema { name: "gh_events", pk: &["repo_id", "id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "id" text NOT NULL,
  "type" text,
  "actor_id" bigint,
  "actor_login" text,
  "created_at" timestamp,
  "payload" text,
  PRIMARY KEY ("repo_id", "id")
);
"# },
    TableSchema { name: "gh_issues", pk: &["repo_id", "number"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "number" integer NOT NULL,
  "title" text,
  "body" text,
  "state" text NOT NULL,
  "author_id" bigint,
  "created_at" timestamp,
  "updated_at" timestamp,
  "closed_at" timestamp,
  PRIMARY KEY ("repo_id", "number")
);
"# },
    TableSchema { name: "gh_jobs", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "run_id" bigint NOT NULL,
  "name" text,
  "status" text,
  "conclusion" text,
  "started_at" timestamp,
  "completed_at" timestamp,
  "runner_name" text
);
"# },
    TableSchema { name: "gh_labeled", pk: &["repo_id", "subject_type", "subject_number", "label_name"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "subject_type" text NOT NULL,
  "subject_number" integer NOT NULL,
  "label_name" text NOT NULL,
  PRIMARY KEY ("repo_id", "subject_type", "subject_number", "label_name")
);
"# },
    TableSchema { name: "gh_labels", pk: &["repo_id", "name"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "name" text NOT NULL,
  "color" text,
  "description" text,
  PRIMARY KEY ("repo_id", "name")
);
"# },
    TableSchema { name: "gh_pr_commits", pk: &["repo_id", "pr_number", "commit_oid"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "pr_number" integer NOT NULL,
  "commit_oid" blob NOT NULL,
  PRIMARY KEY ("repo_id", "pr_number", "commit_oid")
);
"# },
    TableSchema { name: "gh_pr_reviews", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "repo_id" text NOT NULL,
  "pr_number" integer NOT NULL,
  "reviewer_id" bigint,
  "state" text,
  "submitted_at" timestamp,
  "body" text
);
"# },
    TableSchema { name: "gh_pull_requests", pk: &["repo_id", "number"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "number" integer NOT NULL,
  "title" text,
  "body" text,
  "state" text NOT NULL,
  "author_id" bigint,
  "created_at" timestamp,
  "updated_at" timestamp,
  "closed_at" timestamp,
  "merged_at" timestamp,
  "merge_commit_oid" blob,
  "head_ref" text,
  "base_ref" text,
  "additions" integer,
  "deletions" integer,
  "changed_files" integer,
  "is_draft" boolean DEFAULT false NOT NULL,
  "mergeable" text,
  "checks" text,
  "head_oid" blob,
  "base_oid" blob,
  PRIMARY KEY ("repo_id", "number")
);
"# },
    TableSchema { name: "gh_requested_reviewers", pk: &["repo_id", "pr_number", "user_id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "pr_number" integer NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("repo_id", "pr_number", "user_id")
);
"# },
    TableSchema { name: "gh_review_comments", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "repo_id" text NOT NULL,
  "pr_number" integer NOT NULL,
  "path" text,
  "line" integer,
  "side" text,
  "commit_oid" blob,
  "author_id" bigint,
  "body" text,
  "created_at" timestamp,
  "in_reply_to" bigint
);
"# },
    TableSchema { name: "gh_steps", pk: &["job_id", "number"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "job_id" bigint NOT NULL,
  "number" integer NOT NULL,
  "name" text,
  "status" text,
  "conclusion" text,
  "started_at" timestamp,
  "completed_at" timestamp,
  PRIMARY KEY ("job_id", "number")
);
"# },
    TableSchema { name: "gh_users", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "login" text NOT NULL,
  "type" text,
  "name" text
);
"# },
    TableSchema { name: "gh_workflow_runs", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "repo_id" text NOT NULL,
  "workflow_id" bigint,
  "head_oid" blob,
  "head_branch" text,
  "event" text,
  "status" text,
  "conclusion" text,
  "run_number" integer,
  "run_attempt" integer,
  "created_at" timestamp,
  "updated_at" timestamp,
  "run_started_at" timestamp
);
"# },
    TableSchema { name: "gh_workflows", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" bigint PRIMARY KEY,
  "repo_id" text NOT NULL,
  "name" text,
  "path" text,
  "state" text
);
"# },
    TableSchema { name: "refs", pk: &["repo_id", "name"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "repo_id" text NOT NULL,
  "name" text NOT NULL,
  "kind" text NOT NULL,
  "target_oid" blob NOT NULL,
  "is_symbolic" boolean DEFAULT false NOT NULL,
  "upstream" text,
  PRIMARY KEY ("repo_id", "name")
);
"# },
    TableSchema { name: "repos", pk: &["id"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" text PRIMARY KEY,
  "path" text NOT NULL,
  "remote_url" text,
  "host" text,
  "owner" text,
  "name" text,
  "default_branch" text,
  "first_synced_at" timestamp,
  "last_synced_at" timestamp
);
"# },
    TableSchema { name: "sync_state", pk: &["resource"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "resource" text PRIMARY KEY,
  "cursor" text,
  "etag" text,
  "watermark" timestamp,
  "last_synced_at" timestamp,
  "last_error" text
);
"# },
    TableSchema { name: "tree_entries", pk: &["tree_oid", "name"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "tree_oid" blob NOT NULL,
  "name" text NOT NULL,
  "path" text NOT NULL,
  "mode" text NOT NULL,
  "entry_type" text NOT NULL,
  "child_oid" blob NOT NULL,
  PRIMARY KEY ("tree_oid", "name")
);
"# },
    TableSchema { name: "trees", pk: &["oid"], ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "oid" blob PRIMARY KEY,
  "repo_id" text NOT NULL
);
"# },
];

/// Every BOOLEAN `(table, column)` in the schema — for coercing SQLite's 0/1.
pub const BOOL_COLUMNS: &[(&str, &str)] = &[
    ("blobs", "is_binary"),
    ("commits", "is_merge"),
    ("commits", "gpg_signed"),
    ("conflicts", "unresolved"),
    ("gh_pull_requests", "is_draft"),
    ("refs", "is_symbolic"),
];
